-- Migration 006: challenge_invites table
--
-- Stores pending invites for challenges (email, wallet, Steam).
-- Used by POST /api/invites (queue an invite) and GET /api/invites (list).
--
-- status lifecycle: 'queued' → 'sent' | 'accepted' | 'failed'
--
-- Idempotent: safe to run multiple times.

CREATE TABLE IF NOT EXISTS public.challenge_invites (
  id            text          PRIMARY KEY,           -- UUID generated by caller
  challenge_id  bigint        NOT NULL,
  method        text          NOT NULL               -- 'email' | 'wallet' | 'steam'
                CHECK (method IN ('email', 'wallet', 'steam')),
  value         text          NOT NULL,              -- email address / 0x wallet / Steam64 ID
  status        text          NOT NULL DEFAULT 'queued'
                CHECK (status IN ('queued', 'sent', 'accepted', 'failed')),
  created_at    timestamptz   NOT NULL DEFAULT now(),
  updated_at    timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS challenge_invites_challenge_id_idx
  ON public.challenge_invites (challenge_id);

CREATE INDEX IF NOT EXISTS challenge_invites_status_idx
  ON public.challenge_invites (status);
