/**
 * offchain/db/notifications.ts
 *
 * Typed service for public.notifications.
 *
 * Notifications are wallet-scoped messages generated by the system
 * (match results, dispute updates, competition events, achievements, etc.).
 *
 * All functions accept an optional Pool parameter. When omitted, the shared
 * singleton from pool.ts is used.
 */

import type { Pool, PoolClient } from "pg";
import { getPool } from "./pool";

// ─── Types ──────────────────────────────────────────────────────────────────

export type NotificationType =
  | "match_upcoming"
  | "match_result"
  | "competition_started"
  | "competition_completed"
  | "registration_confirmed"
  | "dispute_filed"
  | "dispute_resolved"
  | "achievement_earned";

/** Shape of a row as returned from the DB. */
export type NotificationRow = {
  id: string;
  wallet: string;
  type: NotificationType;
  title: string;
  body: string | null;
  data: Record<string, unknown>;
  read: boolean;
  created_at: Date;
};

// ─── Queries ────────────────────────────────────────────────────────────────

/**
 * Create a new notification for a wallet.
 * Returns the inserted row.
 */
export async function createNotification(
  wallet: string,
  type: NotificationType,
  title: string,
  body?: string | null,
  data?: Record<string, unknown> | null,
  db?: Pool | PoolClient
): Promise<NotificationRow> {
  const client = db ?? getPool();

  const res = await client.query<NotificationRow>(
    `
    INSERT INTO public.notifications (
      wallet, type, title, body, data, read, created_at
    )
    VALUES (lower($1), $2, $3, $4, $5::jsonb, false, now())
    RETURNING *
    `,
    [
      wallet,
      type,
      title,
      body ?? null,
      data ? JSON.stringify(data) : "{}",
    ]
  );

  return res.rows[0];
}

/**
 * List notifications for a wallet, ordered by created_at descending.
 * Supports pagination via limit/offset.
 */
export async function getNotifications(
  wallet: string,
  limit = 50,
  offset = 0,
  db?: Pool | PoolClient
): Promise<NotificationRow[]> {
  const client = db ?? getPool();

  const res = await client.query<NotificationRow>(
    `
    SELECT *
    FROM public.notifications
    WHERE lower(wallet) = lower($1)
    ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
    `,
    [wallet, limit, offset]
  );

  return res.rows;
}

/**
 * Get the count of unread notifications for a wallet.
 */
export async function getUnreadCount(
  wallet: string,
  db?: Pool | PoolClient
): Promise<number> {
  const client = db ?? getPool();

  const res = await client.query<{ cnt: string }>(
    `
    SELECT count(*)::text AS cnt
    FROM public.notifications
    WHERE lower(wallet) = lower($1)
      AND read = false
    `,
    [wallet]
  );

  return Number(res.rows[0]?.cnt ?? "0");
}

/**
 * Mark a single notification as read.
 * Only updates if the wallet matches (ownership check).
 * Returns true if the row was updated.
 */
export async function markRead(
  id: string,
  wallet: string,
  db?: Pool | PoolClient
): Promise<boolean> {
  const client = db ?? getPool();

  const res = await client.query(
    `
    UPDATE public.notifications
    SET read = true
    WHERE id = $1 AND lower(wallet) = lower($2)
    `,
    [id, wallet]
  );

  return (res.rowCount ?? 0) > 0;
}

/**
 * Mark all notifications as read for a wallet.
 * Returns the number of rows updated.
 */
export async function markAllRead(
  wallet: string,
  db?: Pool | PoolClient
): Promise<number> {
  const client = db ?? getPool();

  const res = await client.query(
    `
    UPDATE public.notifications
    SET read = true
    WHERE lower(wallet) = lower($1)
      AND read = false
    `,
    [wallet]
  );

  return res.rowCount ?? 0;
}
